### ISSUE TITLE
code release ?

### ISSUE THREAD

**Issue by jihwanp** [chunmeifeng/CPT#1]
Hi when do you plan to release the code?

And by the way, I think table 4 in the [arxiv](https://arxiv.org/abs/2407.01155) seems incomplete since the proxy tuning and CPT results are not shown.

Thanks

**Comment by hyy-2000** [comment]
Hi Jihwan,

Thanks for your interest in our work, and thank you for pointing out the incomplete table. We also noticed this problem, and the complete table is shown below (we will also upload the complete table in the next update to our paper). The two tables show two different compositions of base/proxy model scale, the smaller one being proxy model.

| method | cars | pets | dtd | flowers |
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| CLIP RN50 zeroshot | 53.84 | 85.68 | 40.27| 66.09 |
| CLIP RN50 finetune | 74.48 | 87.35 | 65.32 | 74.78 |
| CLIP ViT-L/14 zeroshot |  76.74 | **93.49** | 52.93 | 77.54 |
| CLIP ViT-L/14 proxy |  78.94 | 90.27 | 68.19 | 82.58 |
| CLIP ViT-L/14 CPT | **81.69** | 91.58 | **69.31** | **84.75** |
| CLIP ViT-L/14 finetune | 91.92 | 97.00 | 82.07 | 97.35 |


| method | cars | pets | dtd |flowers
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| CLIP ViT-B/16 zeroshot | 63.67 | 89.09 | 42.98 | 71.05 |
| CLIP ViT-B/16 finetune | 86.97 | 95.45 | 78.09 | 95.43 |
| CLIP ViT-L/14 zeroshot | 76.74 | 93.49 | 52.93 | 77.54 |
| CLIP ViT-L/14 proxy | 88.67 | 96.18 | 78.09 | 96.02 |
| CLIP ViT-L/14 CPT | **89.22** | **96.54** | **80.48** | **97.02** |
| CLIP ViT-L/14 finetune | 91.92 | 97.00 | 82.07 | 97.35 |

And for the code release, sorry that we have been otherwise occupied for the past few weeks. The code is currently in a rough state and need some polishing for user convinience. We will do that as soon as we can.

Please feel free to share with us any of your questions or advice!

**Comment by hyy-2000** [comment]
> Hi when do you plan to release the code?
> 
> And by the way, I think table 4 in the [arxiv](https://arxiv.org/abs/2407.01155) seems incomplete since the proxy tuning and CPT results are not shown.
> 
> Thanks

Hi Jihwan,

Thanks for your interest in our work, and thank you for pointing out the incomplete table. We also noticed this problem, and the complete table is shown below (we will also upload the complete table in the next update to our paper). The two tables show two different compositions of base/proxy model scale, the smaller one being proxy model.

| method | cars | pets | dtd | flowers |
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| CLIP RN50 zeroshot | 53.84 | 85.68 | 40.27| 66.09 |
| CLIP RN50 finetune | 74.48 | 87.35 | 65.32 | 74.78 |
| CLIP ViT-L/14 zeroshot |  76.74 | **93.49** | 52.93 | 77.54 |
| CLIP ViT-L/14 proxy |  78.94 | 90.27 | 68.19 | 82.58 |
| CLIP ViT-L/14 CPT | **81.69** | 91.58 | **69.31** | **84.75** |
| CLIP ViT-L/14 finetune | 91.92 | 97.00 | 82.07 | 97.35 |


| method | cars | pets | dtd |flowers
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| CLIP ViT-B/16 zeroshot | 63.67 | 89.09 | 42.98 | 71.05 |
| CLIP ViT-B/16 finetune | 86.97 | 95.45 | 78.09 | 95.43 |
| CLIP ViT-L/14 zeroshot | 76.74 | 93.49 | 52.93 | 77.54 |
| CLIP ViT-L/14 proxy | 88.67 | 96.18 | 78.09 | 96.02 |
| CLIP ViT-L/14 CPT | **89.22** | **96.54** | **80.48** | **97.02** |
| CLIP ViT-L/14 finetune | 91.92 | 97.00 | 82.07 | 97.35 |

And for the code release, sorry that we have been otherwise occupied for the past few weeks. The code is currently in a rough state and need some polishing for user convinience. We will do that as soon as we can.

Please feel free to share with us any of your questions or advice!

**Comment by jihwanp** [comment]
thanks for your reply. i'll be waiting~
